### ISSUE TITLE
Add Fomantic vs Semantic explanation

### ISSUE THREAD

**Issue by douglasg14b** [douglasg14b/awesome-semantic-ui#11]
There should be a section above the ToC that provides an explanation of `what this fomantic thing` is about.

It should answer these questions:

* What is Fomantic?
* Why was it made?
* Should I use it instead?

This will probably be under a section:

## Fomantic?

--write stuff here--

**Comment by douglasg14b** [comment]
Pinging @hammy2899 

I feel like you are better qualified to define the answers to those questions (Or write a piece  for that section) for a description than I am.

**Comment by y0hami** [comment]
@douglasg14b Will do!

I will try get a PR done tomorrow.
