### ISSUE TITLE
Transfer repo?

### ISSUE THREAD

**Issue by douglasg14b** [douglasg14b/awesome-semantic-ui#6]
As it currently stands, this list is more unhelpful than it is helpful since it's littered with deprecated/abandoned projects and new projects and common libraries are not represented.

Pull requests have been sitting idle as well. It's probably time to hand this off? 

I'm relatively active with semantic and the conversations around Fomantic and would be happy to adopt this repo and update & maintain it.

**Comment by websemantics** [comment]
You're right!
I'll transfer the repo as requested but, what happens to my beautiful ascii artwork? :grin:

**Comment by douglasg14b** [comment]
Keep it! Beautiful ascii art is beautiful ascii art.

Reminds me of the graphics I would make as a kid in forums before embedded images where a thing.

**Comment by douglasg14b** [comment]
@websemantics  Thanks!

Time to get to work, lots to do.

By the way, have you heard of https://github.com/fomantic/Fomantic-UI ?

**Comment by websemantics** [comment]
I haven't! Semantic-ui has awesome dev features atop of its elegant design and it's great to see it continue, thanks for the update!
