### ISSUE TITLE
CDN links in resources

### ISSUE THREAD

**Issue by y0hami** [douglasg14b/awesome-semantic-ui#7]
I might be a good idea to link to CDN's in the resources section. Over at FUI we get asked a lot for CDN links.

Fomantic:
  - https://www.jsdelivr.com/package/npm/fomantic-ui

Semantic:
  - https://www.jsdelivr.com/package/npm/semantic-ui
  - https://cdnjs.com/libraries/semantic-ui

**Comment by douglasg14b** [comment]
Good idea, I'll get those added in.

**Comment by douglasg14b** [comment]
This has been added in https://github.com/douglasg14b/awesome-semantic-ui/commit/2873f6ed7b1d2774302751f652d3f62c1a4ce58a
